name: Python Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      run: python -m pip install --upgrade pip poetry

    - name: Install Dependencies
      run: poetry install -C install/apple

    - name: Run Tests
      run: poetry run python -m unittest discover tests/
